# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d3fdaf172e3b267565d593e914bd074cd594c3b6e13e57e9d71d713fb83e906828910cb3a296b899614204e2cd266d260dfe1ad3f0def4176992346551b820

test:
  secret_key_base: 405afcbabbb5f3f00e58e3e0a483d8a2622c866169b14a6272f84d03f4eaca464530ea54ec53cbdd6345e0e4100639c84732c0439be9b7df5dcbb9607128f122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c4cc909388d707c3c69d654bb6f0d07a9dae5ff478833be75149cd6d2500d13e811dfe6d0c2e1a2158dba917a04d8c513043e5ad9e53219f0cc407e19b81250a
